pref("extensions.autopager.enabled", true);
pref("extensions.autopager.debug", false);
pref("extensions.autopager.showpagehold", false);
pref("extensions.autopager.myname", "");
pref("extensions.autopager.smartenable", false);
pref("extensions.autopager.smartexactlymatch", true);
pref("extensions.autopager.smartmaxsize", "2");
pref("extensions.autopager.smarttext", "next|>|下一页|次を表示");
//refer to http://www.teesoft.info/phpbb/viewtopic.php?t=330 fro "NEXT" in Different Languages
pref("extensions.autopager.discoverytext", "navbar|right_arrow|pagN|page|pages|paging|下页|次页|Volgende|Volg|Verder|Напред|Следва|Næste|Nächste|Naechste|Weiter|Vorwärts|Vorwaerts|Volgende|Continue|Onward|Venonta|Seuraava|Suivant|Prochaine|Επόμενη|Næst|Successive|Successiva|Successivo|Prossima|Prossime|Prossimo|Altra|Altro|次へ|다음|Neste|Dalej|Następna|Następne|Następny|Więcej|Próximo|Înainte|Înaintare|Următor|Următoare|След|Следующая|Siguiente|Próxima|Próximos|Nästa|Sonraki|Devam|İlerle");
pref("extensions.autopager.smartlinks", "2");
pref("extensions.autopager.smartMargin", "1");
pref("extensions.autopager.alwaysEnableJavaScript", false);

pref("extensions.autopager.enablehotkeys.ctrlkey", true);
pref("extensions.autopager.enablehotkeys.altkey", true);
pref("extensions.autopager.enablehotkeys.shiftkey", false);
pref("extensions.autopager.disable-hidden-browser", false);
pref("extensions.autopager.loading", "position: fixed; z-index: 2147483647; font-size: 12px; bottom: 1px; max-width:200px;max-height:20px;right: 20px;padding: 1px; background: green none repeat scroll 0%; display:none;");
pref("extensions.autopager.optionstyle", "line-height:normal;width:200px;position: fixed; z-index: 2147483647; font-size: 12px; bottom: 1px; right: 20px;padding: 1px; background: green none repeat scroll 0%; display:none;text-align:left !important;");

pref("extensions.autopager.pagebreak", "clear:both; line-height:20px; background:#E6E6E6; text-align:center;margin-top:20px;margin-bottom:20px;");
pref("extensions.autopager.timeout", "120");
pref("extensions.autopager.lazyload", "1000");
pref("extensions.autopager.update", "48");
pref("extensions.autopager.settingupdatedate", "");
pref("extensions.autopager.noprompt", false);
pref("extensions.autopager.modalprompt", true);
pref("extensions.autopager.disable-by-default", false);
pref("extensions.autopager@mozilla.org.description", "chrome://autopager/locale/autopager.properties");
pref("extensions.autopager.hide-status", false);
pref("extensions.autopager.hide-toolbar-icon", false);
pref("extensions.autopager.hide-context-menu", false);

pref("extensions.autopager.loadingDelayMiliseconds", "100");
pref("extensions.autopager.show-help", false);
pref("extensions.autopager.miniheight", "0.5");
pref("extensions.autopager.defaultheight", "1");
pref("extensions.autopager.minipages", "0");
pref("extensions.autopager.simulateMouseDown",false);
pref("extensions.autopager.show-workshop-in-sidebar",false);
pref("extensions.autopager.tweaking-workshop-result-style",false);
pref("extensions.autopager.show-nav-up",true);
pref("extensions.autopager.show-nav-down",true);
pref("extensions.autopager.show-nav-top",true);
pref("extensions.autopager.show-nav-bottom",true);
pref("extensions.autopager.tweaking-session",false);
pref("extensions.autopager.show-rulecount",true);
pref("extensions.autopager.include-unsafe-rules",false);
pref("extensions.autopager.mini-window-width", "200");
pref("extensions.autopager.mini-window-height", "100");
pref("extensions.autopager.set-x-autopager-httphead", false);
pref("extensions.autopager.ignore-format-version-check", false);
pref("extensions.autopager.anti-anti-autopager", false);
pref("extensions.autopager.work-in-lite-mode", false);
pref("extensions.autopager.with-lite-rules", true);
pref("extensions.autopager.with-lite-discovery", true);
pref("extensions.autopager.hide-lite-discovery-on-no-rules", true);
pref("extensions.autopager.ids", "");
pref("extensions.autopager.with-lite-recommended-rules", true);
pref("extensions.autopager.with-lite-discovery-aways-display", false);
pref("extensions.autopager.lite-discovery-prompted", false);
pref("extensions.autopager.repository-site","http://ap.teesoft.info/");
pref("extensions.autopager.immedialate-load-count","3");
pref("extensions.autopager.show-nav-immedialate-load",true);
pref("extensions.autopager.related-search-discover-url","http://www.google.com/complete/search?client=firefox&q={query}");
pref("extensions.autopager.related-search-prompted",false);
pref("extensions.autopager.related-search-enabled",false);
pref("extensions.autopager.show-rate",true);
